version: "3.7"

networks:
  monitor-net:
    driver: bridge
  chain:

services:
  geth:
    image: ethereum/client-go:${GETH_VERSION}
    entrypoint: /bin/sh
    volumes:
      - ./geth-data:/root/.ethereum
      - ./scripts:/root/scripts:ro
    networks:
      - chain
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8551:8551
      - 6060:6060  # metrics endpoint
    env_file: .env
    command: /root/scripts/start-geth.sh
    #command: /root/scripts/start-geth-prune.sh
    restart: always
  beacon_node:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./scripts:/root/scripts:ro
    networks:
      - chain
    ports:
      - 5052:5052/tcp
      - 5053:5053/tcp
      - 5054:5054/tcp  # metrics endpoint
      - 9000:9000/tcp
      - 9000:9000/udp
    env_file: .env
    command: sh /root/scripts/start-beacon-node.sh
    restart: always
  validator_client:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./scripts:/root/scripts:ro
      - ./validator_keys:/root/validator_keys:ro
    depends_on:
      - beacon_node
    networks:
      - chain
    ports:
      - "5064:5064/tcp"  # metrics endpoint
    env_file: .env
    command: sh /root/scripts/start-validator-client.sh
    restart: always
  mev_boost:
    image: flashbots/mev-boost:latest
    restart: always
    entrypoint:
      - /app/mev-boost
      - -addr
      - 0.0.0.0:18550
      - -mainnet
      - -relay-check
      - -relays
      - "https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net,https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live,https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money"
    networks:
      - chain
    ports:
      - "18550:18550"
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    restart: always
  prometheus:
    build:
      context: ./monitoring/prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net
      - chain
    restart: always 
  grafana:
    build:
      context: ./monitoring/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    restart: always
volumes:
  grafana-data:
  prometheus-data:
  targets:
